FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# Accept build arguments to embed in static assets
ARG VITE_RETRIVA_GATEWAY_BASE_URL
ENV VITE_RETRIVA_GATEWAY_BASE_URL=$VITE_RETRIVA_GATEWAY_BASE_URL
ARG VITE_RETRIVA_ENABLE_VOICE_INPUT
ENV VITE_RETRIVA_ENABLE_VOICE_INPUT=$VITE_RETRIVA_ENABLE_VOICE_INPUT
# --- Authentication (Entra ID) ---
ARG VITE_RETRIVA_AUTH_PROVIDER
ENV VITE_RETRIVA_AUTH_PROVIDER=$VITE_RETRIVA_AUTH_PROVIDER
ARG VITE_RETRIVA_ENTRA_CLIENT_ID
ENV VITE_RETRIVA_ENTRA_CLIENT_ID=$VITE_RETRIVA_ENTRA_CLIENT_ID
ARG VITE_RETRIVA_ENTRA_TENANT_ID
ENV VITE_RETRIVA_ENTRA_TENANT_ID=$VITE_RETRIVA_ENTRA_TENANT_ID
ARG VITE_RETRIVA_ENTRA_AUTHORITY
ENV VITE_RETRIVA_ENTRA_AUTHORITY=$VITE_RETRIVA_ENTRA_AUTHORITY
ARG VITE_RETRIVA_ENTRA_SCOPES
ENV VITE_RETRIVA_ENTRA_SCOPES=$VITE_RETRIVA_ENTRA_SCOPES

RUN npm run build

EXPOSE 5173

# Run the preview server on port 5173
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]
